# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: CrashesOnDLSD
on: workflow_dispatch

jobs:
  chicagocrashes-post:
    runs-on: macOS-latest
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY_DLSD }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET_DLSD }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN_DLSD }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET_DLSD }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - run: |
         brew install pkg-config
         brew install gdal proj geos
         export LDFLAGS="-L/usr/local/opt/libpq/lib"
         export CPPFLAGS="-I/usr/local/opt/libpq/include"
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: RSocrata, tidyverse, ggplot2, lubridate, leaflet, webshot2, viridis, rgeos, leaflet, colorspace, leaflegend, rtweet, devtools, data.table, rmarkdown
      - name: Create and post tweet
        run: Rscript core.R
